import math
import string

class CrazyBot:
    def getProbability(self, n, east, west, south, north):

        self.grid = [[False for i in xrange(100)] for i in xrange(100)]
        self.vx = [-1, 1, 0,  0]
        self.vy = [0, 0, -1, 1]
        self.prob = [west/100.0, east/100.0, south/100.0, north/100.0]

        return self.move(50, 50, n)

    def move(self, x, y, n):
        if self.grid[x][y]:
            return 0
        if n == 0:
            return 1

        self.grid[x][y] = True
        res = 0.0
        for i in xrange(4):
            res += self.move(x+self.vx[i], y+self.vy[i], n-1)*self.prob[i]
        self.grid[x][y] = False

        return res

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, p2, p3, p4, hasAnswer, p5):
    sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str(p0) + str(",") + str(p1) + str(",") + str(p2) + str(",") + str(p3) + str(",") + str(p4))
    print(str("]"))
    obj = CrazyBot()
    startTime = time.clock()
    answer = obj.getProbability(p0, p1, p2, p3, p4)
    endTime = time.clock()
    res = True
    print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
    if (hasAnswer):
        print(str("Desired answer:"))
        print(str("\t") + str(p5))

    print(str("Your answer:"))
    print(str("\t") + str(answer))
    if (hasAnswer):
        res = answer == answer and abs(p5 - answer) <= 1e-9 * max(1.0, abs(p5))

    if (not res):
        print(str("DOESN'T MATCH!!!!"))
    elif ((endTime - startTime) >= 2):
        print(str("FAIL the timeout"))
        res = False
    elif (hasAnswer):
        print(str("Match :-)"))
    else:
        print(str("OK, but is it right?"))

    print(str(""))
    return res

all_right = True


# ----- test 0 -----
p0 = 1
p1 = 25
p2 = 25
p3 = 25
p4 = 25
p5 = 1.0
all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, True, p5) and all_right
# ------------------

# ----- test 1 -----
p0 = 2
p1 = 25
p2 = 25
p3 = 25
p4 = 25
p5 = 0.75
all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, True, p5) and all_right
# ------------------

# ----- test 2 -----
p0 = 7
p1 = 50
p2 = 0
p3 = 0
p4 = 50
p5 = 1.0
all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, True, p5) and all_right
# ------------------

# ----- test 3 -----
p0 = 14
p1 = 50
p2 = 50
p3 = 0
p4 = 0
p5 = 1.220703125E-4
all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, True, p5) and all_right
# ------------------

# ----- test 4 -----
p0 = 14
p1 = 25
p2 = 25
p3 = 25
p4 = 25
p5 = 0.008845493197441101
all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, p4, True, p5) and all_right
# ------------------

if (all_right):
    print(str("You're a stud (at least on the example cases)!"))
else:
    print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# An out-of-control robot is placed on a plane, and it takes n random steps.  At each step, the robot chooses one of four directions randomly and moves one unit in that direction. The probabilities of the robot choosing north, south, east or west are north, south, east and west percent, respectively.
#
# The robot's path is considered simple if it never visits the same point more than once.  (The robot's starting point is always the first visited point.)  Return a double containing the probability that the robot's path is simple.  For example, "EENE" and "ENW" are simple, but "ENWS" and "WWWWSNE" are not ('E', 'W', 'N' and 'S' represent east, west, north and south, respectively).
#
# DEFINITION
# Class:CrazyBot
# Method:getProbability
# Parameters:integer, integer, integer, integer, integer
# Returns:float
# Method signature:def getProbability(self, n, east, west, south, north):
#
#
# NOTES
# -Your return must have relative or absolute error less than 1E-9.
#
#
# CONSTRAINTS
# -n will be between 1 and 14, inclusive.
# -east will be between 0 and 100, inclusive.
# -west will be between 0 and 100, inclusive.
# -south will be between 0 and 100, inclusive.
# -north will be between 0 and 100, inclusive.
# -The sum of east, west, south and north will be 100.
#
#
# EXAMPLES
#
# 0)
# 1
# 25
# 25
# 25
# 25
#
# Returns: 1.0
#
# The robot only takes one step, so it never visits a point more than once.
#
# 1)
# 2
# 25
# 25
# 25
# 25
#
# Returns: 0.75
#
# The robot will visit its starting point twice only if the two moves are in opposite directions.
#
# 2)
# 7
# 50
# 0
# 0
# 50
#
# Returns: 1.0
#
# Here, the only possible directions are north and east, so the robot will never visit the same point twice.
#
# 3)
# 14
# 50
# 50
# 0
# 0
#
# Returns: 1.220703125E-4
#
# Here, the only possible directions are east and west. The only two available paths are "EEEEEEEEEEEEEE" and "WWWWWWWWWWWWWW". The probability is equal to 2 / (2^14).
#
# 4)
# 14
# 25
# 25
# 25
# 25
#
# Returns: 0.008845493197441101
#
# The probability is quite small for n=14.
#
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pfx 2.1.9!
