import math
import string

class InterestingParty:
    def bestInvitation(self, first, second):

        table = first + second

        max_count = 0
        for topic in table:
            count = 0
            for topic1 in first:
                if topic == topic1:
                    count += 1
            for topic2 in second:
                if topic == topic2:
                    count += 1
            if count > max_count:
                max_count = count

        return max_count

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, hasAnswer, p2):
    sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
    for i in range(len(p0)):
        if (i > 0):
            sys.stdout.write(str(","))

        sys.stdout.write(str("\"") + str(p0[i]) + str("\""))

    sys.stdout.write(str("}") + str(",") + str("{"))
    for i in range(len(p1)):
        if (i > 0):
            sys.stdout.write(str(","))

        sys.stdout.write(str("\"") + str(p1[i]) + str("\""))

    sys.stdout.write(str("}"))
    print(str("]"))
    obj = InterestingParty()
    startTime = time.clock()
    answer = obj.bestInvitation(p0, p1)
    endTime = time.clock()
    res = True
    print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
    if (hasAnswer):
        print(str("Desired answer:"))
        print(str("\t") + str(p2))

    print(str("Your answer:"))
    print(str("\t") + str(answer))
    if (hasAnswer):
        res = answer == p2

    if (not res):
        print(str("DOESN'T MATCH!!!!"))
    elif ((endTime - startTime) >= 2):
        print(str("FAIL the timeout"))
        res = False
    elif (hasAnswer):
        print(str("Match :-)"))
    else:
        print(str("OK, but is it right?"))

    print(str(""))
    return res

all_right = True


# ----- test 0 -----
p0 = ["fishing","gardening","swimming","fishing"]
p1 = ["hunting","fishing","fishing","biting"]
p2 = 4
all_right = KawigiEdit_RunTest(0, p0, p1, True, p2) and all_right
# ------------------

# ----- test 1 -----
p0 = ["variety","diversity","loquacity","courtesy"]
p1 = ["talking","speaking","discussion","meeting"]
p2 = 1
all_right = KawigiEdit_RunTest(1, p0, p1, True, p2) and all_right
# ------------------

# ----- test 2 -----
p0 = ["snakes","programming","cobra","monty"]
p1 = ["python","python","anaconda","python"]
p2 = 3
all_right = KawigiEdit_RunTest(2, p0, p1, True, p2) and all_right
# ------------------

# ----- test 3 -----
p0 = ["t","o","p","c","o","d","e","r","s","i","n","g","l","e","r","o","u","n","d","m","a","t","c","h","f","o","u","r","n","i"]
p1 = ["n","e","f","o","u","r","j","a","n","u","a","r","y","t","w","e","n","t","y","t","w","o","s","a","t","u","r","d","a","y"]
p2 = 6
all_right = KawigiEdit_RunTest(3, p0, p1, True, p2) and all_right
# ------------------

if (all_right):
    print(str("You're a stud (at least on the example cases)!"))
else:
    print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# Mr. White is a very versatile person - absolutely everything is interesting to him. Perhaps this is why he has many friends. Quite unfortunately, however, none of his friends are versatile at all. Each of them is interested only in two topics and refuses to talk about anything else. Therefore, each time Mr. White organizes a party, it's a big problem for him to decide whom to invite so that the party is interesting to everybody.
# Now that Mr. White has a lot of experience in organizing parties, he knows for sure that a party will be interesting if and only if there's a topic interesting to each of the invited friends.
#
# You will be given tuple (string)s first and second. The i-th friend of Mr. White is interested in topics first[i] and second[i].
# Return the largest number of friends that Mr. White can invite to his party so that the party will be interesting.
#
# DEFINITION
# Class:InterestingParty
# Method:bestInvitation
# Parameters:tuple (string), tuple (string)
# Returns:integer
# Method signature:def bestInvitation(self, first, second):
#
#
# CONSTRAINTS
# -first will contain between 1 and 50 elements, inclusive.
# -second will contain the same number of elements as first.
# -Each element of first and second will contain between 1 and 15 characters, inclusive.
# -Each character in first and second will be a lowercase letter ('a'-'z').
# -For each valid i, first[i] will not be the same as second[i].
#
#
# EXAMPLES
#
# 0)
# {"fishing", "gardening", "swimming", "fishing"}
# {"hunting", "fishing", "fishing", "biting"}
#
# Returns: 4
#
# This is a very easy case since everybody is interested in "fishing".
#
# 1)
# {"variety", "diversity", "loquacity", "courtesy"}
# {"talking", "speaking", "discussion", "meeting"}
#
# Returns: 1
#
# Despite being interested in "talking", "speaking", "meeting" and so on, these people have nothing to talk about with each other.
#
# 2)
# {"snakes", "programming", "cobra", "monty"}
# {"python", "python", "anaconda", "python"}
#
# Returns: 3
#
# Mr. White can invite friends 0, 1, 3 (0-based) and they will have an interesting evening talking about "python" (or at least Mr. White thinks so).
#
# 3)
# {"t", "o", "p", "c", "o", "d", "e", "r", "s", "i", "n", "g", "l", "e", "r",
#  "o", "u", "n", "d", "m", "a", "t", "c", "h", "f", "o", "u", "r", "n", "i"}
# {"n", "e", "f", "o", "u", "r", "j", "a", "n", "u", "a", "r", "y", "t", "w",
#  "e", "n", "t", "y", "t", "w", "o", "s", "a", "t", "u", "r", "d", "a", "y"}
#
# Returns: 6
#
#
#
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pfx 2.1.9!
